### ISSUE TITLE
Отсутствие обратной связи в время логина

### ISSUE THREAD

**Issue by maksim789456** [TheCrazyWolf/RegistrantCore#1]
В время логина, если логин и/или пароль не правильный нет обратной связи для пользователя.

**Способ воспроизвести:**
- Открыть программу
- В окне для логина и пароля ввести неправильные данные
- Нажать кнопку "Войти"

**Сейчас:**
- Ничего не происходит

**Ожидается:**
- Сообщение о неправильности логина или пароля

**Comment by TheCrazyWolf** [comment]
Фикс будет исправлен в след билдах

**Comment by TheCrazyWolf** [comment]
Исправлено. Будет выпущено обнова
