### ISSUE TITLE
Экран "Водители". Можно создать пустого водителя

### ISSUE THREAD

**Issue by maksim789456** [TheCrazyWolf/RegistrantCore#2]
На экране "Водители" при создании водителя нет валидации на пустые поля, то есть можно создать пустого водителя.

**Способ воспроизвести:**
- Перейти на экран "Водители"
- Нажать кнопку "Новый водитель"
- Сохранить не заполняя никаких полей

**Сейчас:**
- Сохранение проходит успешно, пустой водитель появляется в DataGrid
Подробная информация про пустого пользователя:
![dotnet_cLCy4J1BOu](https://user-images.githubusercontent.com/8225008/115156021-12214280-a08b-11eb-9be1-285ac652f192.png)

**Ожидается:**
- Водитель не сохраняется
- Появляется сообщение и/или подсветка о пустых полях. 
Не обязательно все поля, можно к примеру только минимальный набор (ФИО и номер).

**Comment by TheCrazyWolf** [comment]
не баг а фича

**Comment by TheCrazyWolf** [comment]
Фиксанул в 2.6
