### ISSUE TITLE
Экран "Журнал для КПП". Можно создать пустого внепланового водителя

### ISSUE THREAD

**Issue by maksim789456** [TheCrazyWolf/RegistrantCore#3]
Тот же принцип что и в issue #2. Так же можно создать пустого внепланового водителя не заполняя никаких полей.

**Способ воспроизвести:**
- Перейти на экран "Журнал для КПП"
- Нажать кнопку "Новый водитель (внеплан)"
- Сохранить не заполняя никаких полей

**Сейчас:**
- Сохранение проходит успешно, пустой водитель появляется в зарегистрированных водителей.
![image](https://user-images.githubusercontent.com/8225008/115156653-fec3a680-a08d-11eb-9f51-b65d3476665c.png)

**Ожидается:**
- Водитель не сохраняется
- Появляется сообщение и/или подсветка о пустых полях. 
Не обязательно все поля, можно к примеру только минимальный набор (ФИО и номер).

**Comment by TheCrazyWolf** [comment]
Фиксанул в 2.6
